version: "3"
services:
  povio-app:
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: $NODE_ENV
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      NODE_ENV: $NODE_ENV
      SECRET_TOKEN: $SECRET_TOKEN

  povio-app-db:
    image: mysql
    restart: always
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    env_file: ./.env
    environment:
      NODE_ENV: $NODE_ENV
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT

volumes: 
  db-config:
  db-data:


